apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysql-pv
  namespace: to-do-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ccloud/k8spvc"