apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  namespace: to-do-app
  labels:
    app: mysql
spec:
  nodeName: arunima-u24-worker
  containers:
    - name: mysql-pod
      image: mysql
      envFrom: 
      - configMapRef: 
          name: db-config 
      - secretRef:
          name: db-secret
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc