apiVersion: v1
kind: Service
metadata:
  name: phpwebapp-service
  namespace: to-do-app
spec:
  type: NodePort
  selector:
    app: phpwebapp
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80