apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: to-do-app
spec:
  type: NodePort
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
      nodePort: 31444